{% set name = "databricks-sql-connector" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 961817067989537996b8daa9f8fc8baf1654884acc1b550448a2c684fa23a1d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0,<4.0.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8.0,<4.0.0
    - thrift >=0.16.0,<0.17.0
    - pandas >=1.2.5,<2.2.0
    - pyarrow >=14.0.1,<15.0.0
    - lz4 >=4.0.2,<5.0.0
    - requests >=2.18.1,<3.0.0
    - oauthlib >=3.1.0,<4.0.0
    # more restrictive python 3.11 requirement for noarch
    - numpy >=1.23.4
    - openpyxl >=3.0.10,<4.0.0
    - urllib3 >=1.26
  run_constrained:
    - sqlalchemy >=2.0.21
    - alembic >=1.0.11,<2.0.0

test:
  imports:
    - databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html
  dev_url: https://github.com/databricks/databricks-sql-python

extra:
  recipe-maintainers:
    - xylar
