{% set name = "databricks-sql-connector" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3634fe3d19ee4641cdf76a77854573d9fe234ccdebd20230aaf94053397bc693

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0.0

outputs:
  - name: {{ name }}
    script: install_databricks_sql_connector.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - poetry-core >=1.0.0
      run:
        - python >={{ python_min }},<4.0.0
        - thrift >=0.16.0,<0.21.0
        - pandas >=1.2.5,<2.3.0
        - pyarrow >=14.0.1
        - lz4 >=4.0.2,<5.0.0
        - requests >=2.18.1,<3.0.0
        - oauthlib >=3.1.0,<4.0.0
        # more restrictive python 3.11 requirement for noarch
        - numpy >=1.23.4
        - openpyxl >=3.0.10,<4.0.0
        - urllib3 >=1.26

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - databricks
      commands:
        - pip check

  - name: {{ name }}-with-alembic
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<4.0.0
        - {{ pin_subpackage(name, exact=True) }}
        - alembic >=1.0.11,<2.0.0
        - sqlalchemy >=2.0.21
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - databricks
      commands:
        - pip check

  - name: {{ name }}-with-sqlalchemy
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<4.0.0
        - {{ pin_subpackage(name, exact=True) }}
        - sqlalchemy >=2.0.21
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - databricks
      commands:
        - pip check

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html
  dev_url: https://github.com/databricks/databricks-sql-python

extra:
  recipe-maintainers:
    - xylar
