{% set name = "databricks-sql-connector" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/databricks_sql_connector-{{ version }}.tar.gz
  sha256: 00e3edd495f41cf824624bc87c97af15c5210081629408e3741c37891364cb72

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0.0

outputs:
  - name: {{ name }}
    script: install_databricks_sql_connector.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - poetry-core >=1.0.0
      run:
        - python >={{ python_min }},<4.0.0
        - thrift >=0.16.0,<0.21.0
        # tighter constraint for py >=3.13
        - pandas >=2.2.3,<2.3.0
        - lz4 >=4.0.2,<5.0.0
        - requests >=2.18.1,<3.0.0
        - oauthlib >=3.1.0,<4.0.0
        - openpyxl >=3.0.10,<4.0.0
        - urllib3 >=1.26
        - python-dateutil >=2.8.0,<3.0.0

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - databricks
      commands:
        - pip check

  - name: {{ name }}-with-pyarrow
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<4.0.0
        - {{ pin_subpackage(name, exact=True) }}
        # tighter constraint for py >=3.13
        - pyarrow >=18.0.0
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - databricks
      commands:
        - pip check

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html
  dev_url: https://github.com/databricks/databricks-sql-python

extra:
  recipe-maintainers:
    - xylar
