{% set name = "databricks-sql-connector" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d791a8a5eb8ced1669139e4dce290f1a3667b980e23d640bda44aae71fff53a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.1,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7.1,<4.0
    - thrift >=0.16.0,<0.17.0
    - pandas >=1.3.0,<2.0.0
    # more restrictive python 3.11 requirement for noarch
    - pyarrow >=10.0.1
    - lz4 >=4.0.2,<5.0.0
    - requests >=2.18.1,<3.0.0
    - oauthlib >=3.1.0,<4.0.0
    # more restrictive python 3.11 requirement for noarch
    - numpy >=1.23.4
    - sqlalchemy >=1.3.24,<2.0.0
    - openpyxl >=3.0.10,<4.0.0
    - alembic >=1.8.1,<2.0.0

test:
  imports:
    - databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html

extra:
  recipe-maintainers:
    - xylar
